/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QL_BanGao.view;

import QL_BanGao.dao.GaoDAO;
import QL_BanGao.model.Gao;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import QL_BanGao.dao.LoaiGaoDao;
import QL_BanGao.model.LoaiGao;
import QL_BanGao.dao.NhaCungCapDAO;
import QL_BanGao.model.NhaCungCap;
import javax.swing.JOptionPane;

/**
 *
 * @author Le Van
 */

public class GaoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GaoJPanel
     */
    public GaoJPanel() {
        initComponents();
        showGao();
        set_Cb();
        tatTxt();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    GaoDAO gDao = new GaoDAO();
    LoaiGaoDao lgDao = new LoaiGaoDao();
    NhaCungCapDAO NccDao = new NhaCungCapDAO();

    
    public void clearTXT()
    {   
        txtDD.setText("");
        txtGiaBan.setText("");
        txtGiaNhap.setText("");
        txtMaGao.setText("");
        txtSL.setText("");
        txtIMG.setText("");
    }
    public void tatTxt() {
        txtMaGao.setEnabled(false);
        txtGiaBan.setEnabled(false);
        txtGiaNhap.setEnabled(false);
        cbMaLG.setEnabled(false);
        cbMaNCC.setEnabled(false);
        txtDD.setEnabled(false);
        txtMaGao.setText(gDao.phatsinhMaG());
        btnLuu.setEnabled(false);
        btnThoat.setEnabled(false);
        txtSL.setEnabled(false);
        txtIMG.setEnabled(false);
    }
    int flag = 0;

    public void batTxt() {
        txtGiaBan.setEnabled(true);
        txtGiaNhap.setEnabled(true);
        cbMaLG.setEnabled(true);
        cbMaNCC.setEnabled(true);
        txtDD.setEnabled(true);
        btnLuu.setEnabled(true);
        btnThoat.setEnabled(true);
        txtIMG.setEnabled(true);
        txtSL.setEnabled(true);
        
    }

    public void set_Cb() {
        ArrayList<LoaiGao> listLG = lgDao.getListLG();
        for (LoaiGao n : listLG) {
            cbMaLG.addItem(n.getMaLG());
        }
        ArrayList<NhaCungCap> ListNCC = NccDao.getListNCC();
        for (NhaCungCap n : ListNCC) {
            cbMaNCC.addItem(n.getMaNCC());
        }
    }

    public void showGao() {
        ArrayList<Gao> lGao = gDao.getListGao();
        String[] header = {"MAG", "MALG", "MaNCC", "MoTa", "SoLuong", "GiaBan", "GiaNhap"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        for (Gao g : lGao) {
            model.addRow(new Object[]{g.getMAG(), g.getMALG(), g.getMaNCC(), g.getMota(), g.getSoLuong(), g.getGiaBan(), g.getGiaNhap()});
        }
        jTGao.setModel(model);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTGao = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaGao = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        cbMaNCC = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDD = new javax.swing.JTextPane();
        cbMaLG = new javax.swing.JComboBox<>();
        txtIMG = new javax.swing.JTextField();
        btn_Reload = new javax.swing.JButton();

        jTGao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTGao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTGaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTGao);

        jLabel10.setText("MAG");

        jLabel11.setText("MALG");

        jLabel1.setText("MANCC");

        jLabel2.setText("Đặc điểm");

        jLabel5.setText("Số lượng");

        jLabel6.setText("Giá bán");

        jLabel7.setText("Giá nhập");

        txtSL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSLKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSLKeyTyped(evt);
            }
        });

        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });
        txtGiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiaBanKeyTyped(evt);
            }
        });

        txtGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaNhapActionPerformed(evt);
            }
        });
        txtGiaNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiaNhapKeyTyped(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtDD);

        txtIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMGActionPerformed(evt);
            }
        });

        btn_Reload.setText("Tải lại");
        btn_Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(60, 60, 60)
                                .addComponent(txtMaGao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel1))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMaNCC, 0, 121, Short.MAX_VALUE)
                                    .addComponent(cbMaLG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIMG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Reload))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(btn_Reload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaGao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void them() {
        Gao tempt = new Gao();
        tempt.setMAG(txtMaGao.getText());
        tempt.setGiaBan(Float.parseFloat(txtGiaBan.getText()));
        tempt.setGiaNhap(Float.parseFloat(txtGiaNhap.getText()));
        tempt.setMALG((String) cbMaLG.getSelectedItem());
        tempt.setMaNCC((String) cbMaNCC.getSelectedItem());
        tempt.setMota(txtDD.getText());
        tempt.setLinkImage(txtIMG.getText());
        tempt.setSoLuong(Integer.parseInt(txtSL.getText()));
        float gianhap = Float.parseFloat(txtGiaNhap.getText());
        float giaban = Float.parseFloat(txtGiaBan.getText());
        if(gianhap < giaban)
        { int t = gDao.themGao(tempt);
        if (t != 0) {
            JOptionPane.showMessageDialog(btnThoat, "Thêm thành công");
            tatTxt();
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
            clearTXT();
        } else {
            JOptionPane.showMessageDialog(btnThoat, "Lỗi");
        }
        }  
        else
            JOptionPane.showMessageDialog(btnThoat, "Giá bán thấp hơn giá nhập");
        showGao();

    }

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void txtGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaNhapActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        batTxt();
        btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
        flag = 1;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         try 
       {
             if(txtMaGao.getText().isEmpty() || txtGiaBan.getText().isEmpty())
                JOptionPane.showMessageDialog(btnXoa,"Thiếu thông tin");
             else 
                {
                  int response = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xóa?",
                          "Xác nhận xóa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                     if (response == JOptionPane.YES_OPTION) {
                   int i  = gDao.xoaGao(txtMaGao.getText());
                   if(i != 0)
                   {JOptionPane.showMessageDialog(btnXoa,"Đã xóa");
                   clearTXT();
                    showGao();
                   }
                    else
                         JOptionPane.showMessageDialog(btnXoa,"Lỗi");
                    }
                }
                } catch (Exception e) {
                    e.printStackTrace();
        }
           
    }//GEN-LAST:event_btnXoaActionPerformed

    public void sua()
    {   
          
      float gianhap = Float.parseFloat(txtGiaNhap.getText());
      float giaban = Float.parseFloat(txtGiaBan.getText());
         try {
            if(txtGiaBan.getText().isEmpty()|| txtGiaNhap.getText().isEmpty()||txtSL.getText().isEmpty())
            {JOptionPane.showMessageDialog(btnXoa,"Thiếu thông tin");
            }
            else if(gianhap < giaban)
            { 
                JOptionPane.showMessageDialog(btnThoat, "Giá nhập thấp hơn giá bán");
            }
            else
            {
                int kq = gDao.updateGao(txtMaGao.getText(), txtDD.getText(),Integer.parseInt(txtSL.getText()), Float.parseFloat(txtGiaBan.getText()), Float.parseFloat(txtGiaNhap.getText()));
                  if(kq != 0)
                   {JOptionPane.showMessageDialog(btnXoa,"Update thành công");
                    showGao();
                    clearTXT();
                         jTGao.setEnabled(true);
                   }
                    else
                         JOptionPane.showMessageDialog(btnXoa,"Lỗi");
                    }
            }      

        catch (Exception e) {
        }
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        jTGao.setEnabled(false);
        flag = 2;
        txtDD.setEnabled(true);
        txtGiaBan.setEnabled(true);
        txtGiaNhap.setEnabled(true);
        txtSL.setEnabled(true);
        btnLuu.setEnabled(true);
        btnThoat.setEnabled(true);
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
      
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (flag == 1)
            them();
        else
            sua();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
           clearTXT();
            tatTxt();
            btnXoa.setEnabled(true);
            btnSua.setEnabled(true);
            btnThem.setEnabled(true);
            btnThoat.setEnabled(false);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jTGaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTGaoMouseClicked
        // TODO add your handling code here:
        ArrayList<Gao> g = gDao.getListGao();
        int vt = jTGao.getSelectedRow();
        Gao prGao = new Gao();
        if (vt != -1) {
            prGao = g.get(vt);
            txtDD.setText(prGao.getMota());
            txtGiaBan.setText(Float.toString(prGao.getGiaBan()));
            txtGiaNhap.setText(Float.toString(prGao.getGiaBan()));
            cbMaLG.setSelectedItem(prGao.getMALG());
            cbMaNCC.setSelectedItem(prGao.getMaNCC());
            txtMaGao.setText(prGao.getMAG());
            txtSL.setText(Integer.toString(prGao.getSoLuong()));
            String ma = prGao.getMaNCC();
        }


    }//GEN-LAST:event_jTGaoMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Gao> search= gDao.findG(txtTim.getText());
        String[] header = {"MAG", "MALG", "MaNCC", "MoTa", "SoLuong", "GiaBan", "GiaNhap"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        model.setRowCount(0);
        jTGao.setModel(model);
        for (Gao g : search) {
            model.addRow(new Object[]{g.getMAG(), g.getMALG(), g.getMaNCC(), g.getMota(), g.getSoLuong(), g.getGiaBan(), g.getGiaNhap()});
        }
        jTGao.setModel(model);
        
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMGActionPerformed

    private void txtSLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSLKeyPressed

    private void txtSLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtSLKeyTyped

    private void txtGiaBanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaBanKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtGiaBanKeyTyped

    private void txtGiaNhapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaNhapKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtGiaNhapKeyTyped

    private void btn_ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReloadActionPerformed
        // TODO add your handling code here:
        showGao();
    }//GEN-LAST:event_btn_ReloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_Reload;
    private javax.swing.JComboBox<String> cbMaLG;
    private javax.swing.JComboBox<String> cbMaNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTGao;
    private javax.swing.JTextPane txtDD;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtIMG;
    private javax.swing.JTextField txtMaGao;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
